.TH VENOM 1 "October 2014"

.SH NAME
venom - GTK+ client for Tox

.SH SYNOPSIS
.B venom

.SH DESCRIPTION
.B venom
is a cross-platform graphical user interface for Tox written in Vala
using GTK+.

.SH OPTIONS
.BI venom
has no command line options.

.SH SEE ALSO
.B Tox Wiki:
https://wiki.tox.im/Venom

.SH AUTHOR
This manual page was written by kytv <killyourtv@i2pmail.org> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
